# Generated by Django 3.2.7 on 2021-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pageCount', models.IntegerField(default=0)),
                ('thumbnailUrl', models.CharField(max_length=256, null=True)),
                ('shortDescription', models.CharField(max_length=250, null=True)),
                ('longDescription', models.TextField(null=True)),
            ],
        ),
    ]
